# find JPLogger
message("STUFF")
IF(NOT(JPLogger_LIBRARY AND JPLogger_INCLUDE_DIR))
	# search for include and library path
	FIND_PATH(JPLogger_INCLUDE_DIR  libJPLogger.hpp PATHS ${LOCAL_INC} )
	FIND_LIBRARY(JPLogger_LIBRARY JPLogger PATHS ${LOCAL_LIBS} )

	IF(JPLogger_INCLUDE_DIR AND JPLogger_LIBRARY)
		SET(JPLogger_FOUND TRUE)
		MESSAGE(STATUS "Found JPLogger: ${JPLogger_LIBRARY}")

	ELSE(JPLogger_INCLUDE_DIR AND JPLogger_LIBRARY)
		SET(JPLogger_FOUND FALSE)
		MESSAGE(SEND_ERROR "Could NOT find JPLogger")
	ENDIF(JPLogger_INCLUDE_DIR AND JPLogger_LIBRARY)
ENDIF( NOT ( JPLogger_LIBRARY AND JPLogger_INCLUDE_DIR) )
